- name: Install Nginx
  yum:
     name: nginx
     state: latest

- name: Start service ngnix
  ansible.builtin.service:
    name: nginx
    state: started


- name: Download zip file
  get_url:
    url: https://github.com/log-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip
    force_basic_auth: yes


- name: Create frontend
  ansible.builtin.file:
    path: /tmp/frontend
    state: directory
    mode: '0755'

- name: Unarchive frontend
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /tmp/frontend
    remote_src: yes


- name: Remove ngnix content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent