
- name: install nginx
  yum:
    name: nginx
    state: latest


- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
- name: start nginx
  service:
    name: nginx
    state: enabled