
- name: install nginx
  yum:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Download code
  include_role:
    name: common
    tasks_from: download
- name: Remove ngnix html file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
