
- name: install nginx
  yum:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Download code
  include_role:
    name: common
    tasks_from: download
- name: Remove ngnix html file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy frontend static
  ansible.builtin.copy:
    src: /tmp/frontend-main
    dest: /usr/share/nginx/html
    remote_src: yes
    validate: /usr/sbin/visudo -csf %s
- name: start nginx
  service:
    name: nginx
    state: restart
    enabled: yes