
- name: install nginx
  yum:
    name: nginx
    state: latest


- name: restart nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Download code
  include_role:
    name: common
    tasks_from: download
