
- name: install nginx
  yum:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: download frontend content
  include_role:
    name: common
    task_from: download
  vars:
    APP_LOCATION: /usr/share/nginx/html/

