- name: Download "{{COMPO}}" code
  include_role:
    name: common
    tasks_from: download
- name: installing nginx
  yum:
    name: nginx
    state: latest

- name: copy https documents installing nginx
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Enable Nginx Service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes



