
- name: install nginx
  yum:
    name: nginx
    state: latest


- name: restart nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Download code
  include_role:
    name: common
    tasks_from: download


- name: Remove nginx html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy the Htdocs content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static
    dest: /usr/share/nginx/html
    remote_src: yes
