- name: example
  hosts: all
  become: true
  tasks:
    - name: Download foo.conf
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /tmp/apache-tomcat-8.5.78.tar.gz
        validate_certs: no
    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-8.5.78.tar.gz
        dest: /opt


    - name: Change the working directory to some/ before executing the command
      ansible.builtin.shell: chmod -R 777 .
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/
    - name: Change the working directory to some/ before executing the command
      ansible.builtin.shell: chmod -R 777 .
      args:
        chdir: /opt/apache-tomcat-8.5.78/logs/
    - name: Change the working direct to somedir/ before executing the command
      ansible.builtin.shell: sudo chown -R centos:centos .
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/

    - name: Change the working direct to somedir/ before executing the command
      ansible.builtin.shell: sudo chown -R centos:centos .
      args:
        chdir: /opt/apache-tomcat-8.5.78/logs/

    - name: Change the working directory to somedir/ befoexecuting the command
      ansible.builtin.shell: bash startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/







