- name: example
  hosts: all
  become: true
  tasks:
    - name: Download foo.conf
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.zip
        dest: /tmp/apache-tomcat-8.5.78.zip
        validate_certs: no
    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-8.5.78.zip
        dest: /opt
        remote_src: yes

    - name: change bin permision
      ansible.builtin.shell: chmod -R 777 .
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/
    - name: change logs permision
      ansible.builtin.shell: chmod -R 777 .
      args:
        chdir: /opt/apache-tomcat-8.5.78/logs/
    - name: change bin user
      ansible.builtin.shell: sudo chown -R centos:centos .
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/

    - name: change bin user
      ansible.builtin.shell: sudo chown -R centos:centos .
      args:
        chdir: /opt/apache-tomcat-8.5.78/logs/

    - name: startup tomcat
      ansible.builtin.shell: bash startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.78/bin/







