- name: setup tomcat
  hosts: all
  become: true

- name: Download foo.conf
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.zip --no-check-certificate
    dest: /tmp






