---
- name: Install Apache Tomcat10 using ansible
  hosts: server
  become: true
  tasks:

    - name: Install java
      yum:
        name: java
        state: latest
    - name: Download tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz --no-check-certificate"
        dest: /tmp/apache-tomcat-9.0.64.tar.gz
        mode: '0440'



    - name: Unarchive a file
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.64.tar.gz
        dest: /usr/
        remote_src: yes



    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true








