- name: setup tomcat
  hosts: all
  became: true
  tasks:
    - name: download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /tmp/apache-tomcat-10.0.20.tar.gz

    - name: Extract
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.0.20.tar.gz
        dest: /tmp

    - name: cd
      ansible.builtin.shell: cd bin
    - name: start tomcat
          ansible.builtin.shell: bash startup.sh
