- name: setup tomcat
  hosts: all

  tasks:
    - name: download & unarchive tomcat10
      unarchive:
            src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
            dest: /tmp
            remote_src: yes







