- name: installing nginx
  yum:
    name: nginx
    state: latest


- name: download  code
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPO}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: copy https documents installing nginx
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes


- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes

- name: Enable Nginx Service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
